import React from 'react';
import { Activity, ArrowRight, CircleDot, Mail, Users } from 'lucide-react';
import { ArchiveState } from '../../state/useArchiveStore';
import { discoveryReactions, staffLiveState } from '../../data/archiveActivityData';
import { staffRoster } from '../../data/foundationData';

export const ArchiveActivityPanel: React.FC<{ store: ArchiveState }> = ({ store }) => {
  const recent = discoveryReactions.filter(item => store.discoveredAnomalies.includes(item.anomalyId)).slice(-3).reverse();
  const staffChanges = staffRoster.map(staff => ({ staff, live: staffLiveState(staff.id, store) })).filter(item => item.live).slice(0, 3);
  return (
    <section className="archive-activity-panel" aria-labelledby="archive-activity-title">
      <header><div><span>LIVE ARCHIVE ACTIVITY</span><h2 id="archive-activity-title">The institution is responding</h2><p>Updates generated by recovered evidence—not a second navigation checklist.</p></div><Activity size={24} /></header>
      <div className="archive-activity-grid">
        <div className="activity-column"><div className="activity-label"><CircleDot size={15} /> RECENT CONSEQUENCES</div>
          {recent.length ? recent.map(item => <button key={item.anomalyId} onClick={() => store.navigate(item.view)}><strong>{item.activity}</strong><small>Open related record <ArrowRight size={13} /></small></button>) : <div className="activity-empty">No evidence has disturbed the archive yet. The ordinary catalog remains stable.</div>}
        </div>
        <div className="activity-column"><div className="activity-label"><Users size={15} /> STAFF MOVEMENT</div>
          {staffChanges.length ? staffChanges.map(({ staff, live }) => <button key={staff.id} onClick={() => store.navigate('STAFF')}><strong>{staff.name}</strong><small>{live?.status} — {live?.note}</small></button>) : <div className="activity-empty">All listed staff remain at their ordinary assignments.</div>}
        </div>
        <div className="activity-column activity-comms"><div className="activity-label"><Mail size={15} /> PRIVATE CHANNELS</div><strong>{store.unreadDmCount} unread archive message{store.unreadDmCount === 1 ? '' : 's'}</strong><p>Investigators may contact you when a discovery changes an active record.</p><button className="btn btn-secondary" onClick={() => store.navigate('DIRECT_MESSAGES')}>Open messages <ArrowRight size={14} /></button></div>
      </div>
    </section>
  );
};
